# -*- coding: utf-8 -*-
import scrapy
from scrapy.contrib.linkextractors import LinkExtractor
from scrapy.contrib.spiders import CrawlSpider, Rule

from romdownloader.items import FileItem


class CmSpider(CrawlSpider):
    name = 'miui'
    allowed_domains = ['www.clockworkmod.com']
    start_urls = [
        'http://en.miui.com/download-262.html',
        'http://en.miui.com/download-240.html',
        'http://en.miui.com/download-261.html',
        'http://en.miui.com/download-229.html',
        'http://en.miui.com/download-218.html',
        'http://en.miui.com/download-101.html',
        'http://en.miui.com/download-226.html',
        'http://en.miui.com/download-82.html',
        'http://en.miui.com/download-37.html',
        'http://en.miui.com/download-2.html',
        'http://en.miui.com/download-1.html',
        'http://en.miui.com/download-4.html',
        'http://en.miui.com/download-183.html',
        'http://en.miui.com/download-29.html',
        'http://en.miui.com/download-3.html',
        'http://en.miui.com/download-232.html',
        'http://en.miui.com/download-5.html',
        'http://en.miui.com/download-75.html',
        'http://en.miui.com/download-213.html',
        'http://en.miui.com/download-115.html',
        'http://en.miui.com/download-72.html',
        'http://en.miui.com/download-6.html',
        'http://en.miui.com/download-57.html',
        'http://en.miui.com/download-253.html',
        'http://en.miui.com/download-186.html',
        'http://en.miui.com/download-8.html',
        'http://en.miui.com/download-206.html',
        'http://en.miui.com/download-10.html',
        'http://en.miui.com/download-61.html',
        'http://en.miui.com/download-12.html',
        'http://en.miui.com/download-63.html',
        'http://en.miui.com/download-14.html',
        'http://en.miui.com/download-182.html',
        'http://en.miui.com/download-252.html',
        'http://en.miui.com/download-185.html',
        'http://en.miui.com/download-7.html',
        'http://en.miui.com/download-9.html',
        'http://en.miui.com/download-256.html',
        'http://en.miui.com/download-11.html',
        'http://en.miui.com/download-13.html',
        'http://en.miui.com/download-111.html',
        'http://en.miui.com/download-15.html',
        'http://en.miui.com/download-17.html',
        'http://en.miui.com/download-68.html',
        'http://en.miui.com/download-34.html',
        'http://en.miui.com/download-19.html',
        'http://en.miui.com/download-217.html',
        'http://en.miui.com/download-180.html',
        'http://en.miui.com/download-221.html',
        'http://en.miui.com/download-237.html',
        'http://en.miui.com/download-255.html',
        'http://en.miui.com/download-110.html',
        'http://en.miui.com/download-112.html',
        'http://en.miui.com/download-16.html',
        'http://en.miui.com/download-114.html',
        'http://en.miui.com/download-18.html',
        'http://en.miui.com/download-238.html',
        'http://en.miui.com/download-35.html',
        'http://en.miui.com/download-20.html',
        'http://en.miui.com/download-56.html',
        'http://en.miui.com/download-234.html',
        'http://en.miui.com/download-220.html',
        'http://en.miui.com/download-105.html',
        'http://en.miui.com/download-207.html',
        'http://en.miui.com/download-239.html',
        'http://en.miui.com/download-45.html',
        'http://en.miui.com/download-113.html',
        'http://en.miui.com/download-245.html',
        'http://en.miui.com/download-21.html',
        'http://en.miui.com/download-23.html',
        'http://en.miui.com/download-44.html',
        'http://en.miui.com/download-48.html',
        'http://en.miui.com/download-216.html',
        'http://en.miui.com/download-118.html',
        'http://en.miui.com/download-22.html',
        'http://en.miui.com/download-24.html',
        'http://en.miui.com/download-132.html',
        'http://en.miui.com/download-134.html',
        'http://en.miui.com/download-36.html',
        'http://en.miui.com/download-251.html',
        'http://en.miui.com/download-104.html',
        'http://en.miui.com/download-38.html',
        'http://en.miui.com/download-74.html',
        'http://en.miui.com/download-40.html',
        'http://en.miui.com/download-25.html',
        'http://en.miui.com/download-125.html',
        'http://en.miui.com/download-225.html',
        'http://en.miui.com/download-190.html',
        'http://en.miui.com/download-242.html',
        'http://en.miui.com/download-127.html',
        'http://en.miui.com/download-212.html',
        'http://en.miui.com/download-129.html',
        'http://en.miui.com/download-131.html',
        'http://en.miui.com/download-50.html',
        'http://en.miui.com/download-248.html',
        'http://en.miui.com/download-133.html',
        'http://en.miui.com/download-250.html',
        'http://en.miui.com/download-71.html',
        'http://en.miui.com/download-203.html',
        'http://en.miui.com/download-39.html',
        'http://en.miui.com/download-58.html',
        'http://en.miui.com/download-254.html',
        'http://en.miui.com/download-41.html',
        'http://en.miui.com/download-26.html',
        'http://en.miui.com/download-224.html',
        'http://en.miui.com/download-189.html',
        'http://en.miui.com/download-43.html',
        'http://en.miui.com/download-126.html',
        'http://en.miui.com/download-211.html',
        'http://en.miui.com/download-128.html',
        'http://en.miui.com/download-30.html',
        'http://en.miui.com/download-130.html',
        'http://en.miui.com/download-117.html',
        'http://en.miui.com/download-106.html',
        'http://en.miui.com/download-27.html',
        'http://en.miui.com/download-244.html',
        'http://en.miui.com/download-116.html',
        'http://en.miui.com/download-187.html',
        'http://en.miui.com/download-241.html',
        'http://en.miui.com/download-66.html',
        'http://en.miui.com/download-235.html',
        'http://en.miui.com/download-123.html',
        'http://en.miui.com/download-257.html',
        'http://en.miui.com/download-227.html',
        'http://en.miui.com/download-46.html',
        'http://en.miui.com/download-197.html',
        'http://en.miui.com/download-122.html',
        'http://en.miui.com/download-124.html',
        'http://en.miui.com/download-28.html',
        'http://en.miui.com/download-79.html',
        'http://en.miui.com/download-47.html',
        'http://en.miui.com/download-32.html',
        'http://en.miui.com/download-49.html',
        'http://en.miui.com/download-230.html',
        'http://en.miui.com/download-51.html',
        'http://en.miui.com/download-70.html',
        'http://en.miui.com/download-119.html',
        'http://en.miui.com/download-53.html',
        'http://en.miui.com/download-233.html',
        'http://en.miui.com/download-136.html',
        'http://en.miui.com/download-121.html',
        'http://en.miui.com/download-137.html',
        'http://en.miui.com/download-78.html',
        'http://en.miui.com/download-259.html',
        'http://en.miui.com/download-193.html',
        'http://en.miui.com/download-31.html',
        'http://en.miui.com/download-69.html',
        'http://en.miui.com/download-52.html',
        'http://en.miui.com/download-120.html',
        'http://en.miui.com/download-222.html',
        'http://en.miui.com/download-60.html',
        'http://en.miui.com/download-243.html',
        'http://en.miui.com/download-64.html',
        'http://en.miui.com/download-260.html',
        'http://en.miui.com/download-98.html',
        'http://en.miui.com/download-247.html',
        'http://en.miui.com/download-246.html',
        'http://en.miui.com/download-33.html',
        'http://en.miui.com/download-236.html',
        'http://en.miui.com/download-81.html',
        'http://en.miui.com/download-83.html',
        'http://en.miui.com/download-85.html',
        'http://en.miui.com/download-231.html',
        'http://en.miui.com/download-102.html',
        'http://en.miui.com/download-87.html',
        'http://en.miui.com/download-89.html',
        'http://en.miui.com/download-91.html',
        'http://en.miui.com/download-108.html',
        'http://en.miui.com/download-93.html',
        'http://en.miui.com/download-95.html',
        'http://en.miui.com/download-97.html',
        'http://en.miui.com/download-99.html',
        'http://en.miui.com/download-84.html',
        'http://en.miui.com/download-86.html',
        'http://en.miui.com/download-103.html',
        'http://en.miui.com/download-88.html',
        'http://en.miui.com/download-107.html',
        'http://en.miui.com/download-92.html',
        'http://en.miui.com/download-109.html',
        'http://en.miui.com/download-94.html',
        'http://en.miui.com/download-191.html',
        'http://en.miui.com/download-96.html',
        'http://en.miui.com/download-196.html',
        'http://en.miui.com/download-161.html',
        'http://en.miui.com/download-215.html',
        'http://en.miui.com/download-178.html',
        'http://en.miui.com/download-146.html',
        'http://en.miui.com/download-100.html',
        'http://en.miui.com/download-198.html',
        'http://en.miui.com/download-163.html',
        'http://en.miui.com/download-249.html',
        'http://en.miui.com/download-148.html',
        'http://en.miui.com/download-200.html',
        'http://en.miui.com/download-165.html',
        'http://en.miui.com/download-219.html',
        'http://en.miui.com/download-150.html',
        'http://en.miui.com/download-167.html',
        'http://en.miui.com/download-204.html',
        'http://en.miui.com/download-152.html',
        'http://en.miui.com/download-169.html',
        'http://en.miui.com/download-59.html',
        'http://en.miui.com/download-223.html',
        'http://en.miui.com/download-188.html',
        'http://en.miui.com/download-154.html',
        'http://en.miui.com/download-76.html',
        'http://en.miui.com/download-42.html',
        'http://en.miui.com/download-208.html',
        'http://en.miui.com/download-171.html',
        'http://en.miui.com/download-139.html',
        'http://en.miui.com/download-156.html',
        'http://en.miui.com/download-210.html',
        'http://en.miui.com/download-173.html',
        'http://en.miui.com/download-141.html',
        'http://en.miui.com/download-158.html',
        'http://en.miui.com/download-80.html',
        'http://en.miui.com/download-175.html',
        'http://en.miui.com/download-143.html',
        'http://en.miui.com/download-65.html',
        'http://en.miui.com/download-195.html',
        'http://en.miui.com/download-160.html',
        'http://en.miui.com/download-214.html',
        'http://en.miui.com/download-177.html',
        'http://en.miui.com/download-145.html',
        'http://en.miui.com/download-67.html',
        'http://en.miui.com/download-162.html',
        'http://en.miui.com/download-179.html',
        'http://en.miui.com/download-147.html',
        'http://en.miui.com/download-199.html',
        'http://en.miui.com/download-164.html',
        'http://en.miui.com/download-149.html',
        'http://en.miui.com/download-135.html',
        'http://en.miui.com/download-166.html',
        'http://en.miui.com/download-151.html',
        'http://en.miui.com/download-73.html',
        'http://en.miui.com/download-168.html',
        'http://en.miui.com/download-90.html',
        'http://en.miui.com/download-205.html',
        'http://en.miui.com/download-153.html',
        'http://en.miui.com/download-170.html',
        'http://en.miui.com/download-138.html',
        'http://en.miui.com/download-155.html',
        'http://en.miui.com/download-77.html',
        'http://en.miui.com/download-209.html',
        'http://en.miui.com/download-172.html',
        'http://en.miui.com/download-140.html',
        'http://en.miui.com/download-62.html',
        'http://en.miui.com/download-258.html',
        'http://en.miui.com/download-157.html',
        'http://en.miui.com/download-174.html',
        'http://en.miui.com/download-142.html',
        'http://en.miui.com/download-228.html',
        'http://en.miui.com/download-194.html',
        'http://en.miui.com/download-159.html',
        'http://en.miui.com/download-176.html',
        'http://en.miui.com/download-144.html',]
    
    def parse(self, response):
        url1s = response.xpath('//span[@class="span_download"]/a/@href').extract()
        for url1 in url1s:
            item = FileItem()
            item['url'] = url1
            yield item
        
        url2s = response.xpath('//a[@class="btn_5"]/@href').extract()
        for url2 in url2s:
            item = FileItem()
            item['url'] = url2
            yield item
        
#        i = RomdownloaderItem()
        #i['domain_id'] = response.xpath('//input[@id="sid"]/@value').extract()
        #i['name'] = response.xpath('//div[@id="name"]').extract()
        #i['description'] = response.xpath('//div[@id="description"]').extract()
#        return i
